[package]
name = "proxy_app"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rotator = { path = "../crates/rotator" }
models = { path = "../crates/models" }
proxy_config = { package = "config", path = "../crates/config" }
axum = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true, features = ["util", "limit"] }
tower-http = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true }
chrono = { workspace = true }
